# Generated by Django 2.1.2 on 2018-11-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractname', models.CharField(max_length=50)),
                ('sha256', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('share1', models.CharField(max_length=100)),
                ('share2', models.CharField(max_length=100)),
                ('share3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractname', models.CharField(max_length=50)),
                ('sha256', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('share1', models.CharField(max_length=100)),
                ('share2', models.CharField(max_length=100)),
                ('share3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_role', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=20)),
                ('c_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract2',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Member'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Member'),
        ),
    ]
