# Generated by Django 2.1.2 on 2018-10-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractname', models.CharField(max_length=50)),
                ('md5', models.CharField(max_length=100)),
                ('sha1', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
