# Generated by Django 2.1.2 on 2018-11-06 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractname', models.CharField(max_length=50)),
                ('sha256', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('share1', models.CharField(max_length=100)),
                ('share2', models.CharField(max_length=100)),
                ('share3', models.CharField(max_length=100)),
                ('share4', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Member')),
            ],
        ),
    ]
