# Generated by Django 2.1.2 on 2018-11-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_role',
            field=models.IntegerField(default=0),
        ),
    ]
